### ISSUE TITLE
Erroneous link

### ISSUE THREAD

**Issue by pivic** [Penetrum-Security/Security-List#4]
I believe the following link is erroneous:

> - USB Write Blocker https://legility.com/

For clarification: the URL seems to lead to a company that deals in legalities. Older links seem to lead to https://www.legility.com/landing-pages/download-usb-write-blocker/ but this link is dead.

**Comment by Penetrum-Security** [comment]
Hey! Sorry for the delay, we just got access back to the Github. I'll check this out and fix it as soon as I can.

**Comment by Penetrum-Security** [comment]
The closest thing I've found is some code that hasn't been reviewed, so I think we're just going to remove it

**Comment by Penetrum-Security** [comment]
I replaced it with Anti USB https://github.com/Penetrum-Security/Security-List/commit/af9c8043dae2e0241dac8fa8529be866157d5c80
